package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-08  03:10:07 PM
 */
public class EngAcmt extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(14);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: BookingCancelSuccess
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BookingCancelSuccess", "BookingCancelSuccess.wav", "Your booking is cancelled successfully"); 

		// phrase: BookingCancelFailed
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BookingCancelFailed", "BookingCancelFailed.wav", "Unable to cancel booking."); 

		// phrase: BookingNoNotFound
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BookingNoNotFound", "BookingNoNotFound.wav", "You have entered invalid Booking Number"); 

		// phrase: BookingConfirmed
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BookingConfirmed", "BookingConfirmed.wav", "Your Booking is Confirmed"); 

		// phrase: ConfirmBooking
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ConfirmBooking", "ConfirmBooking.wav", "For Confirm Booking"); 

		// phrase: EditBooking
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EditBooking", "EditBooking.wav", "For Edit Booking"); 

		// phrase: CancelBooking
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CancelBooking", "CancelBooking.wav", "For Cancel Booking"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-14  09:54:44 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(EngAcmt.PHRASE_MAP, phraseName));
	}
}
