package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  12:54:10 PM
 */
public class EngMainMenu extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(12);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: ForNewBooking
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForNewBooking", "ForNewBooking.wav", "For New Booking"); 

		// phrase: ForLastBookingDetails
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForLastBookingDetails", "ForLastBookingDetails.wav", "For Last Booking Details"); 

		// phrase: ForModifyBooking
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForModifyBooking", "ForEditBooking.wav", "For Edit Booking Details"); 

		// phrase: ForCancelBooking
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForCancelBooking", "ForCancelBooking.wav", "For Cancel Booking"); 

		// phrase: NoInput
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoInput", "NoInputEngMainMenu.wav", "You have not selected any option yet."); 

		// phrase: NoMatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoMatch", "NoMatchEngMainMenu.wav", "You have entered Invalid Option"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-08  05:11:28 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(EngMainMenu.PHRASE_MAP, phraseName));
	}
}
