package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  02:39:39 PM
 */
public class EngPC extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(26);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: EnterNoPerson
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EnterNoPerson", "EnterNoPerson.wav", "Enter Number of Persons"); 

		// phrase: NoInputNoPerson
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoInputNoPerson", "NoInputNoPerson.wav", "you didn\'t enter the number of persons yet"); 

		// phrase: NoMatchNoPerson
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoMatchNoPerson", "NoMatchNoPerson.wav", "You are entered wrong input."); 

		// phrase: EnterDurationInHrs
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EnterDurationInHrs", "EnterDurationInHrs.wav", "Enter Duration in Hours"); 

		// phrase: EnterDate
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EnterDate", "EnterDate.wav", "Enter Date in  (Year - Month - Day)    format."); 

		// phrase: EnterBookingNo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EnterBookingNo", "EnterBookingNo.wav", "Enter Your Booking Number"); 

		// phrase: EnterTime
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "EnterTime", "EnterTime.wav", "Enter Time in (hours,minutes) format"); 

		// phrase: NoInputDuration
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoInputDuration", "NoInputDuration.wav", "you didn\'t enter the duration yet. Please"); 

		// phrase: NoMatchDuration
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoMatchDuration", "NoMatchDuration.wav", "you have entered Invalid duration"); 

		// phrase: NoInputDate
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoInputDate", "NoInputDate.wav", "you didn\'t enter the date yet. please"); 

		// phrase: NoMatchDate
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoMatchDate", "NoMatchDate.wav", "You have entered invalid date format."); 

		// phrase: NoInputTime
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoInputTime", "NoInputTime.wav", "you didn\'t enter the Time yet"); 

		// phrase: NoMatchTime
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoMatchTime", "NoMatchTime.wav", "You have entered Invalid Time format. Please"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-15  12:19:05 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(EngPC.PHRASE_MAP, phraseName));
	}
}
