package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  12:20:55 PM
 */
public class HotelTableBooking extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(22);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: WelcomeAcmt
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "WelcomeAcmt", "WelcomeAcmt.wav", "Welcome to Hotel Table Booking"); 

		// phrase: ExitAcmt
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ExitAcmt", "ExitAcmt.wav", "Thank You for calling hotel table booking"); 

		// phrase: WaitingToTransferCallAcmt
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "WaitingToTransferCallAcmt", "WaitingToTransferCallAcmt.wav", "Please wait. Your call will transfer to our agent.."); 

		// phrase: ForExit
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForExit", "ForExit.wav", "For Exit"); 

		// phrase: ForTransferToAgent
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForTransferToAgent", "ForTransferToAgent.wav", "For Call Transfer to our Agent"); 

		// phrase: ForChangeLanguage
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForChangeLanguage", "ForChangeLanguage.wav", "For Change Language"); 

		// phrase: ForMainMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ForMainMenu", "ForMainMenu.wav", "For Main Menu"); 

		// phrase: MoreInvalidValues
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MoreInvalidValues", "MoreInvalidValues.wav", "Sorry, You have enter invalid value frequently"); 

		// phrase: MoreInvalidChoice
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MoreInvalidChoice", "MoreInvalidChoice.wav", "Sorry, You have choose wrong Choice on more times."); 

		// phrase: TryAgainLater
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "TryAgainLater", "TryAgainLater.wav", "Please try again later"); 

		// phrase: SometingWrong
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "SometingWrong", "SometingWrong.wav", "Sorry, Something wrong."); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-08  05:55:03 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(HotelTableBooking.PHRASE_MAP, phraseName));
	}
}
