/**
 * Last generated by Orchestration Designer at: 2023-FEB-01  04:20:23 PM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class PinPCPrompt extends com.avaya.sce.runtime.Prompt {

	// {{START:CLASS:FIELDS
	// }}END:CLASS:FIELDS

	/**
	 * Constructor for PinPCPrompt.
	 */
	public PinPCPrompt() {
		// {{START:CLASS:CONSTRUCTOR
		super();
		// }}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-FEB-06  12:40:07 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("PinPCPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}

	@Override
	public void updatePrompt(SCESession mySession) {
		super.updatePrompt(mySession);
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("PinPCPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		setTimeout(1, 8000);
		setBargin(1, true);

		System.out.println("UpdatePrompt in PinPCPrompt");

		String isExistCustomer = mySession
				.getVariableField(IProjectVariables.VALIDATION, IProjectVariables.VALIDATION_FIELD_IS_EXIST_CUSTOMER)
				.getStringValue();

		if ("true".equals(isExistCustomer)) {
			add(1, new com.avaya.sce.runtime.PhraseVariableElement("audioPath:ExistCustomerEnterPin",
					com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
			System.out.println("ExistCustomer");
		} else {
			add(1, new com.avaya.sce.runtime.PhraseVariableElement("audioPath:NewCustomerEnterPin",
					com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
			System.out.println("NewCustomer");
		}

	}
}
